#!/bin/sh
# vi: set ft=sh expandtab shiftwidth=4 tabstop=4:
set -e
set -u

call() { echo " $@" ; "$@" ; }

tld="$(git rev-parse --show-cdup)"
if test -n "$tld" ; then
    cd -- "$tld"
fi

find .git_externals -type d -name .git | while read gitdir ; do
    dir="$(dirname -- "$gitdir")"
    if test -d "$dir" ; then
    (
        cd -- "$dir"
        echo $dir
        call git svn fetch
        call git svn rebase
    )
    fi
done
